# Generated by Django 5.2.1 on 2025-05-22 23:49

from django.db import migrations

def insert_passenger_types(apps, schema_editor):
    PassengerType = apps.get_model('users', 'PassengerType')
    PassengerType.objects.get_or_create(name='Student', defaults={'description': 'Estudiante'})
    PassengerType.objects.get_or_create(name='Professor', defaults={'description': 'Profesor'})
    PassengerType.objects.get_or_create(name='Staff', defaults={'description': 'Personal'})

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_insert_user_types'),
    ]

    operations = [
        migrations.RunPython(insert_passenger_types),
    ]
