# Generated by Django 5.2.1 on 2025-05-22 22:55

from django.db import migrations


def insert_user_types(apps, schema_editor):
    UserType = apps.get_model('users', 'UserType')
    UserType.objects.get_or_create(name='SystemAdmin', defaults={'description': 'Administrador del sistema'})
    UserType.objects.get_or_create(name='CollegeAdmin', defaults={'description': 'Administrador institucional'})
    UserType.objects.get_or_create(name='Driver', defaults={'description': 'Conductor'})
    UserType.objects.get_or_create(name='Passenger', defaults={'description': 'Pasajero'})

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_college'),
    ]

    operations = [
        migrations.RunPython(insert_user_types),
    ]
