# Generated by Django 5.2.1 on 2025-07-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_user_validator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengertype',
            name='passenger_type_id',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='user_type_id',
        ),
        migrations.AddField(
            model_name='passengertype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='usertype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
