# Generated by Django 5.2.1 on 2025-07-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_passengertype_passenger_type_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='denied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='reason_denied',
            field=models.TextField(blank=True, null=True),
        ),
    ]
