services:
  web:
    container_name: web
    build:
      context: .
    ports:
      - "8000:8000"
    command: ["sh", "-c", "./wait-for-it.sh uway_database:5432 -- ./start.sh"]
    volumes:
        - .:/app
    env_file:
      - .env
    depends_on:
      - uway_database
      - redis

  uway_database:
    container_name: database
    image: postgis/postgis
    platform: linux/amd64
    restart: always
    volumes:
      - uway_db_data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
  redis:
    container_name: redis
    image: redis:alpine
    platform: linux/amd64
    ports:
      - "6379:6379"

  celery:
    container_name: celery
    build:
      context: .
    command: celery -A uway_backend worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web
      - redis

  celery_beat:
    container_name: celery_beat
    build:
      context: .
    command: celery -A uway_backend beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - celery
      - redis

volumes:
  uway_db_data:
