# Generated by Django 5.2.1 on 2025-05-22 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'college',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('hex_code', models.CharField(max_length=7, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'color',
            },
        ),
        migrations.CreateModel(
            name='CollegeColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.college')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='colleges.color')),
            ],
            options={
                'db_table': 'college_color',
                'unique_together': {('college', 'color')},
            },
        ),
    ]
