# Generated by Django 5.2.1 on 2025-05-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='email',
            field=models.EmailField(blank=True, max_length=320, null=True),
        ),
    ]
