# Generated by Django 5.2.1 on 2025-05-23 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_college_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
