# Generated by Django 5.2.1 on 2025-06-01 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_insert_vehicles_types'),
        ('vehicles', '0003_insert_vehicle_categories'),
    ]

    operations = [
    ]
