# Generated by Django 5.2.1 on 2025-07-19 17:12

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_passengertrip_validated_and_more'),
        ('vehicles', '0007_alter_vehicle_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_location',
        ),
        migrations.CreateModel(
            name='VehicleLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('date', models.DateTimeField()),
                ('trip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_locations', to='trips.trip')),
            ],
            options={
                'db_table': 'vehicle_location',
            },
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
