# Generated by Django 5.2.1 on 2025-07-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_vehicle_user_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='denied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='reason_denied',
            field=models.TextField(blank=True, null=True),
        ),
    ]
