# Generated by Django 5.2.1 on 2025-07-26 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_vehicle_denied_vehicle_reason_denied'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelocation',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_locations', to='vehicles.vehicle'),
        ),
    ]
