# Generated by Django 5.2.1 on 2025-07-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
