# Generated by Django 5.2.1 on 2025-07-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
