# Generated by Django 5.2.1 on 2025-07-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trip_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengertrip',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passengertrip',
            name='validation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
