# Generated by Django 5.2.1 on 2025-07-27 01:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_rate_passenger_alter_rate_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('trip', 'passenger')},
        ),
    ]
